//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exfob1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exfob1.ResourceMessage", typeof(ResourceMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le {0} est un champ requis !.
        /// </summary>
        public static string Erreur1002 {
            get {
                return ResourceManager.GetString("Erreur1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreurde misejour, ce objet nexiste pas en base de donnéées.
        /// </summary>
        public static string ErreurNotFound_Misejour {
            get {
                return ResourceManager.GetString("ErreurNotFound_Misejour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas de donnees Pour cette requette.
        /// </summary>
        public static string ErrurNotFound {
            get {
                return ResourceManager.GetString("ErrurNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur Suppression, ce objet nexiste plus en base de donnees.
        /// </summary>
        public static string ErrurNotFound_Suppression {
            get {
                return ResourceManager.GetString("ErrurNotFound_Suppression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Operation.
        /// </summary>
        public static string Message001 {
            get {
                return ResourceManager.GetString("Message001", resourceCulture);
            }
        }
    }
}
